Application/Django/ACHACHA/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('member/', include('member.urls')),
    path('fast_search/', include('fast_search.urls')), 
    path('all_search/', include('all_search.urls')),
    path('acha_money/', include('acha_money.urls')),
]

urlpatterns += static(settings.MEDIAFILES_LOCATION, document_root=settings.MEDIAFILES_LOCATION)

Application/Django/member/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = 'member'

urlpatterns = [
    # path('register/', RegisterView.as_view()),
    path('', views.index),
    path('login/', views.LoginView_withlogger.as_view(template_name='member/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('delivery/', views.delivery, name='delivery'),
    path('delivery/delivery_detail/<int:posts_id_pk>/', views.delivery_detail, name='delivery_detail'),
    path('owner/', views.owner, name='owner'),
    path('owner/owner_detail/<int:posts_id_pk>/', views.owner_detail, name='owner_detail'),
    path('mypage/', auth_views.LoginView.as_view(template_name='member/mypageindex.html'), name='mypage'),
    path('auth/', views.SmsSendView.as_view(), name='auth'),
    path('auth_check/', views.SMSVerificationView.as_view(), name='auth_check')
]

Application/Django/member/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import requests
from random import randint
from django.utils import timezone
import json
import time
import datetime
import hmac
import base64
import hashlib

# Create your models here.
class request(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

class implement(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

class customuser(AbstractUser):
    # 기본적으로 제공하는 필드 외에 원하는 필드를 적어준다.
    phone = models.IntegerField(unique=True, null=False, blank =False)
    address = models.CharField(max_length=50)

class Authentication(models.Model):
    phone_number = models.CharField('휴대폰 번호', max_length=30)
    auth_number = models.CharField('인증번호', max_length=30)

    class Meta:
        db_table = 'authentications' # DB 테이블명
        verbose_name_plural = "휴대폰인증 관리 페이지" # Admin 페이지에서 나타나는 설명

Application/Django/member/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import customuser

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = customuser
        fields = ("username", "password1", "password2", "email", "phone", "address")

Application/Django/member/views.py
from enum import auto
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .models import request
from .models import implement
from .forms import UserForm
from acha_money.models import Posts, UserDeal


# Python
import json, requests, time, random

# Django
from django.views import View
from django.http import JsonResponse
from .utils import make_signature
from .models import Authentication
from acha_money.models import UserDeal
from acha_money.models import Posts

# logger import 
from . import logger

from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView



class LoginView_withlogger(LoginView): 
    def log_check(request):
        logger.trace_logger(request)


def register(request):
    logger.trace_logger(request) # view 로그 추적 

    if request.method == "POST":
        form = UserForm(request.POST)

        if form.is_valid():
            # form.address = request.POST['address'].encode('utf-8')
            form.save()
            

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('http://localhost:8000')
    else:
        form = UserForm()
        
    return render(request, 'member/register.html', {'form': form})

def index(request):
    logger.trace_logger(request) # view 로그 추적 
    request_list = request.objects.order_by('-create_date')
    context = {'request_list': request_list}
    return render(request, 'member/request.html', context)


def owner(request):
    logger.trace_logger(request) # view 로그 추적 
    user_name = request.user
    posts = Posts.objects.raw("SELECT * FROM posts join user_deal \
                             on posts.posts_id_pk = user_deal.posts_id \
                        where user_deal.deal = 'owner' and user_deal.users_id= %s", [user_name])
    # post = Posts.objects.filter(users_id=request.user)
    # post = post.extra(tables=['user_deal'], where=['posts.posts_id_pk=user_deal.posts_id'])
    # print(post)
    return render(request, 'member/owner.html', {'posts': posts})


# class requestList():
#     template_name = "member/request.html"
#     context_object_name = 'request'
#
#     def get_queryset(self, **kwargs):
#         queryset = UserDeal.objects.filter(users_id = self.request.session.get('user'))
#         return queryset
#
# def request(self, request):
#     seller = UserDeal.objects.filter(users_id=self.request.session.get('user'))
#     return render(request, 'member/request.html', {'seller': seller})



def delivery(request):

    
    logger.trace_logger(request) # view 로그 추적 

    user_name = request.user
    posts = Posts.objects.raw("SELECT * FROM posts join user_deal \
                             on posts.posts_id_pk = user_deal.posts_id \
                        where user_deal.deal = 'delivery' and user_deal.users_id=%s", [user_name])

    # post = post.extra(tables=['user_deal'], where=['posts.posts_id_pk=user_deal.posts_id']).distinct()
    return render(request, 'member/delivery.html', {'posts': posts})



# Create your views here.

# def login(request):
#     return render(request, 'member/login.html')




# 인증번호 발송
class SmsSendView(View):
    def send_sms(self, phone_number, auth_number):
        sid = "ncp:sms:kr:292968693103:achacha_auth"
        sms_uri = "/sms/v2/services/{}/messages".format(sid)
        sms_url = "https://sens.apigw.ntruss.com{}".format(sms_uri)
            
        acc_key_id  = "D3HFVghtWIESI6SSXmlE"          
        timestamp = str(int(time.time() * 1000))  

        body = {
            "type": "SMS", 
            "contentType": "COMM",
            "from": "01083873393", 
            "content": f"[아차차 인증번호:{auth_number}]", 
            "messages": [{"to": f"{phone_number}"}] 
        }
        response = requests.post(
        sms_url, data=json.dumps(body),
        headers={"Content-Type": "application/json; charset=utf-8",
                "x-ncp-apigw-timestamp": timestamp,
                "x-ncp-iam-access-key": acc_key_id,
                "x-ncp-apigw-signature-v2": make_signature(timestamp)
                }
         )
        return response.text
        
    def post(self, request):
        # data = json.loads(request.body)
        data = json.loads(request.body)
        print("Phone : ", data)
        if Authentication.DoesNotExist: # DB 입력 로직 작성
            input_mobile_num = data
            auth_num = random.randint(10000, 100000)
            Authentication.objects.create(
                phone_number=input_mobile_num,
                auth_number=auth_num,
            ).save()
            self.send_sms(phone_number=input_mobile_num, auth_number=auth_num)
            return JsonResponse({'message': '인증번호 발송 및 DB 입력완료'}, status=200)

        else:
            auth_mobile = Authentication.objects.get(phone_number=input_mobile_num)
            auth_mobile.auth_number = auth_num
            auth_mobile.save()
            self.send_sms(phone_number=data, auth_number=auth_num)
            return JsonResponse({'message': '인증번호 발송완료'}, status=200)


# 인증번호 확인
class SMSVerificationView(View):
    def post(self, request):
        phone_number = request.POST.get('phone_number')
        auth_number = request.POST.get('auth_number')
        print("phone_number : ", phone_number, "| auth_number : ", auth_number)
        try:
            verification = Authentication.objects.get(phone_number=phone_number)

            if verification.auth_number == auth_number:
                verification.delete() # 인증된 내역은 삭제
                return JsonResponse({'message': '인증 완료되었습니다.'}, status=200)

            else:
                return JsonResponse({'message': '인증 실패입니다.'}, status=400)

        except Authentication.DoesNotExist:
            return JsonResponse({'message': '해당 휴대폰 번호가 존재하지 않습니다.'}, status=400)
        
        
        
def delivery_detail(request, posts_id_pk):
    posts = Posts.objects.filter(posts_id_pk=posts_id_pk)
    deal = posts.values()
    context = {
        "posts": posts,
        "deal": deal,
    }
    return render(request, 'member/delivery_detail.html', context)

def owner_detail(request, posts_id_pk):
    posts = Posts.objects.filter(posts_id_pk=posts_id_pk)
    deal = posts.values()[0]
    context = {
        "posts": posts,
        "deal": deal,
    }
    return render(request, 'member/owner_detail.html', context)

Application/Django/templates/member/delivery.html
{% extends "base/base.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link href="{% static 'acha_money/css/base.css' %}" rel="stylesheet" type="text/css">
</head>
<body>
{% if user.is_authenticated %}
<div class="container-fluid">
    {% if not posts %}
    <div class="alarm">
        아차차! 대신 수령한 내역이 없습니다.<br>
        <a href="/acha_money/">대신 수령 해보기</a>
    </div>
    {% else %}

    <div class="lost_items">
        <div class="col-lg-6 mb-4">
            {% for post in posts %}
            <div class="right" onclick="location.href='delivery_detail/{{post.posts_id_pk}}/'">
                <div class="title">{{ post.title }}</div>
                <span class="created_at">{{ post.created_at}}</span>
                <br>
                <span class="cost">{{ post.cost }} 원</span>
                <hr>
            {% endfor %}

                </div>
            </div>
        </div>

    {% endif %} 
{% else %}
<div class="container-fluid">
    <div class="row">
        <div class="card border-left-warning shadow w-100 py-2" id="login">
            <div class="card-body">
                <div class="text-lg font-weight-bold text-warning text-uppercase mb-1">ACHACHA</div>
                <p class="card-text">로그인을 해주세요</p>
                <a href="/member/login" class="btn btn-primary">로그인 하러가기</a>
            </div>
        </div>
        <div class="card border-left-warning shadow w-100 py-2" style="margin-bottom: 5px;">
            <div class="card-body">
                <div class="text-lg font-weight-bold text-warning text-uppercase mb-1">ACHACHA</div>
                <p class="card-text">아직 회원이 아니라면 회원가입을 해주세요</p>
                <a href="/member/register" class="btn btn-primary">회원가입 하러가기</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; ACHACHA 2022</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="js/demo/datatables-demo.js"></script>
</div>
</body>
{% endblock %}
</html>

Application/Django/templates/member/login.html
<!DOCTYPE html>
{% extends "base/base.html" %}
{% block content %}
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">
</head>

<body>

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <!-- 추가된 부분 !-->
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">로그인</h1>
                                    </div>
                                    <form method="post" action="{% url 'member:login' %}" class="user">
                                        {% csrf_token %}
                                        {% include "form_errors.html" %}
                                        <div class="form-group">
                                            <!-- <label for="username">사용자ID</label> -->
                                            <input type="text" class="form-control form-control-user" name="username" id="username"
                                                value="{{ form.username.value|default_if_none:'' }}" placeholder="아이디">
                                        </div>
                                        <div class="form-group">
                                            <!-- <label for="password">비밀번호</label> -->
                                                <input type="password" class="form-control form-control-user" name="password" id="password"
                                                    value="{{ form.password.value|default_if_none:'' }}" placeholder="비밀번호">
                                        </div>
                                            <button type="submit" class="btn btn-primary btn-user btn-block">로그인</button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="big" href="/member/register">계정을 만드세요!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>
{% endblock %}
</html>

Application/Django/templates/member/login_org.html
<!DOCTYPE html>
<html lang="en">
{% extends "base/base.html" %}
{% block content %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <!-- 추가된 부분 !-->
                                    <div class="text-center">
                                        <form method="post" action="{% url 'member:login' %}">
                                            {% csrf_token %}
                                            {% include "form_errors.html" %}
                                            <div class="mb-3">
                                                <label for="username">사용자ID</label>
                                                <input type="text" class="form-control" name="username" id="username"
                                                    value="{{ form.username.value|default_if_none:'' }}">
                                            </div>
                                            <div class="mb-3">
                                                <label for="password">비밀번호</label>
                                                 <input type="password" class="form-control" name="password" id="password"
                                                     value="{{ form.password.value|default_if_none:'' }}">
                                            </div>
                                             <button type="submit" class="btn btn-primary">로그인</button>
                                            </form>
                                    </div>
                                    <hr>
                                    <div class="text-center">
                                        <a class="big" href="/member/register">계정을 만드세요!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>
{% endblock %}
</html>

Application/Django/templates/member/register.html
<!DOCTYPE html>
<html lang="en">
{% extends "base/base.html" %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
      
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
    </script>
    <!-- <script>
        $(function() {
            // 인증번호 발송
            $("#phoneChk").click(function(){
                var phone = $("#phone").val();
                $.ajax({
                    type:"POST",
                    url:"{% url 'member:auth' %}",
                    dataType: "json",
                    data: JSON.stringify(phone),
                    cache : false,
                    success:function(data){
                        if(phone == ""){
                            $(".successPhone").text("유효한 번호를 입력해 주세요.");
                            $(".successPhone").css("color","red");
                            $("#phone").attr("autofocus",true);
                        }else{	        		
                            $("#phone2").attr("disabled",false);
                            $("#phoneChk2").css("display","inline-block");
                            $(".successPhone").text("인증번호 발송이 완료되었습니다.");
                            $(".successPhoneChk").text("인증번호를 입력한 뒤 본인인증을 눌러주세요.");
                            $(".successPhoneChk").css("color","green");
                            $("#phone").attr("readonly",true);
                        }
                    }
                });
            });
            // 인증번호 확인
            $("#phoneChk2").click(function(){
                $.ajax({
                    type:"POST",
                    url:"{% url 'member:auth_check' %}",
                    dataType: "json",
                    data: {'phone_number':$("#phone").val(), 'auth_number':$("#phone2").val()},
                    success:function(data){
                        $("#phone2").attr("disabled");
                        $("#phoneChk2").css("display","inline-block");
                        $(".successPhoneChk").text("인증되었습니다.");
                        $(".successPhoneChk").css("color","green");
                        $("#phone").attr("readonly",true);
                    },
                    error:function(error){
                        $(".successPhoneChk").text("인증번호를 다시 확인해 주세요.");
                        $(".successPhoneChk").css("color","red");
                    }
                });
            });
            // 전화번호 인증 유효성 검사
            var join = document.register;
            var input = $("#phone2");
            join.onsubmit = function() { 
                if (input.val()=="") { 
                alert("전화번호를 인증해 주세요.")
                $("#phone").focus(); 
                return false; 
                }
             }
        });
    </script> -->
    <style>
        .doubleChk{
            background-color: #d7d7d7;
            color: black;
            display: inline;
            border: 1px solid;
            border-color: #EAECF4;
            padding: 9px;
            font-size: 12px;
            border-radius:4px;
        }
        .doubleChk:hover{
            background-color: #b1aeae;
        }
        label{
            display: block;
        }
        #phone, #phone2{
            display: inline;
            width: calc(100% - 100px);
      
        }
        .successPhoneChk, .successPhone{
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container my-3">
        <form method="post" name="register" action="{% url 'member:register' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="mb-3">
                <label for="username">사용자 이름</label>
                <input type="text" class="form-control" name="username" id="username"
                       value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password1">비밀번호</label>
                <input type="password" class="form-control" name="password1" id="password1"
                       value="{{ form.password1.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="password2">비밀번호 확인</label>
                <input type="password" class="form-control" name="password2" id="password2"
                       value="{{ form.password2.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="email">이메일</label>
                <input type="text" class="form-control" name="email" id="email"
                       value="{{ form.email.value|default_if_none:'' }}">
            </div>
            <div class="mb-3">
                <label for="phone">전화번호</label>
                <input type="text" class="form-control" name="phone" id="phone"
                    value="{{ form.phone.value|default_if_none:'' }}">
                <span id="phoneChk" class="doubleChk">인증번호 발송</span>
                <div class="point successPhone"></div>         
            </div>
            <div class="mb-3">
                <label for="phone2">인증번호</label>
                <input id="phone2" class="form-control", type="text" name="phone2" title="인증번호 입력" disabled required/>
                <span id="phoneChk2" class="doubleChk">인증번호 확인</span>
			    <div class="point successPhoneChk"></div>
            </div>
            <div class="mb-3">
                <label for="address">주소</label>
                <input type="text" class="form-control" name="address" id="address"
                       value="{{ form.address.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="btn btn-primary">회원 가입하기</button>
        </form>
    </div>
{% endblock %}

</body>
</html>